version: '3.7'
services:
  web:
    image: pghiuzan/grapefruit_booking_api:nginx
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./infrastructure/docker/nginx/Dockerfile
    depends_on:
      - app

  app:
    image: pghiuzan/grapefruit_booking_api:fpm
    build:
      context: ./
      dockerfile: ./infrastructure/docker/fpm/Dockerfile
    depends_on:
      - redis
